### ISSUE TITLE
[Bug?]: `yarn rw setup graphiql dbAuth` fails on v6.4.0

### ISSUE THREAD

**Issue by staticshock** [redwoodjs/redwood#9581]
### What's not working?

Example:

```
$ yarn rw setup graphiql dbAuth --id 1
✖ encryptSession is not a function
◼ Generating file in src/lib/generateGraphiQLHeader.{js,ts}...
◼ Importing generated headers into createGraphQLHandler
◼ Installing packages...
encryptSession is not a function
```

This used to work on v6.3.3, and broke when `encryptSession` was introduced, in c80df9b30ffbfbf1b9b75af92938a9941215a075.

### How do we reproduce the bug?

Run `yarn rw setup graphiql dbAuth --id 1`.

### What's your environment? (If it applies)

MacOS M1

### Are you interested in working on this?

- [X] I'm interested in working on this
