### ISSUE TITLE
Error: Cannot find module 'types/graphql' after upgrade to v0.33.0

### ISSUE THREAD

**Issue by sundeer** [redwoodjs/redwood#2788]
Getting this error after upgrading to v0.33.0 when I try to import enums from src/(api/web)/types/graphql.d.ts. Before upgrading, I used 'graphql-code-generator' package but configured it to generate regular '.ts' files and of course importing enums worked just fine. I see in docs for graphql-code-generator that the 'constEnums' config option for the 'typescript' plugin would probably fix this I think. See in the docs: [constEnums](https://www.graphql-code-generator.com/docs/plugins/typescript)

**Comment by thedavidprice** [comment]
Hi @sundeer There are a couple of possibilities here. During the upgrade process, things might be out of sync between your projects node_modules + yarn.lock and the Redwood packages. You could try the following:
- delete node_modules from root, web/, and api/
- delete yarn.lock
- run `yarn install`
- then try yarn rw dev

And/or you might have a use case that Redwood's TS features currently don't support very well. @dac09 has started a discussion over here on the [Redwood Forums in this post](https://community.redwoodjs.com/t/community-help-wanted-typescript-feedback-v0-33-x/2177). I do recommend you reply to that thread to coordinate with Danny directly as he's one of the leads on Redwood TS and would greatly appreciate your feedback and project needs.

**Comment by peterp** [comment]
Hey @sundeer The configuration for those generators is over here for the schema:
https://github.com/redwoodjs/redwood/blob/a4d664f0a6a3e3029d75b4c186e4525cd5da1973/packages/internal/src/generate/graphqlSchema.ts#L24-L63

and here for the operations: 
https://github.com/redwoodjs/redwood/blob/a4d664f0a6a3e3029d75b4c186e4525cd5da1973/packages/internal/src/generate/typeDefinitions.ts#L186-L206

I think it would be nice if this configuration was "pluggable" by users. Does GraphQL codegen have a typical place where configuration files are stored? Perhaps we can read and merge configuration options into the code snippets above.

**Comment by sundeer** [comment]
Thanks @peterp. A `codegen.{yml, json}` file in the project root is the standard location. Would be nice to be able to add options to the plugins from some kind of config file or even a section in `config.json`.

**Comment by peterp** [comment]
@sundeer 🆒 🆒 🆒 , in the meantime I suggest manually moving the file into `src/types/graphql.ts`

**Comment by thedavidprice** [comment]
@peterp @dac09 How would you like to prioritize this one? Here's my interpretation based on the conversation above:
- add to v1-priority
- not a requirement for v1-rc release

?

**Comment by dac09** [comment]
The main issue with this one is actually not the generator, where we can easily add this config. However, its going to work in dev and fail in build because:

a) **If we switch to generating a `graphql.ts` file instead of `graphql.d.ts`**
Redwood's babel config doesn't currently look inside the types folder, if you're using enums (and not const enums), its a problem because the expecation may be that you're able to use the enums at runtime in your deployed app, and not just in dev

b) **If we continue using `.d.ts` but swithc to const enums**
We can't use const enums when transpiling typescript with babel (apparently, not verified yet)
> The isolated module flag prohibits the use of const enums. This flag is on if you compile your stuff with Babel and use TypeScript just as a type checker. Important to know!

Just needs further investigation really. For now only thing I can suggest is to have enums you want in your src files (i.e. duplicate the type) instead of importing from `types/graphql`.

@sundeer - very happy to help you investigate this further if you're interested in contributing?

**Comment by sundeer** [comment]
@dac09 Looks like Prisma does not use ts enums when generating types for the client. This is from my prisma `index.d.ts` file.
```
/**
 * Enums
 */

// Based on
// https://github.com/microsoft/TypeScript/issues/3192#issuecomment-261720275

export const RoleName: {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

export type RoleName = (typeof RoleName)[keyof typeof RoleName]
```
If graphql-code-generator could support this, that would sidestep the problem altogether. I'll open an issue over there.

**Comment by peterp** [comment]
@sundeer Can you take a look at #2830, this made enums usable in my current project.
