### ISSUE TITLE
[Bug?]: v4.0.0 Decouple Auth not working with dbAuth

### ISSUE THREAD

**Issue by dennemark** [redwoodjs/redwood#7288]
### What's not working?

After upgrading to v4 and running `yarn rw setup auth dbAuth` the registering of a new user throws the following error:

```
api | 18:18:03 🌲 Starting a postgresql pool with 13 connections.
api | 18:18:03 🚨 this.engine.dmmf is not a function
api | 18:18:03 🌲 request completed 73ms
api | 18:18:03 🌲 incoming request GET xxx /auth?method=getToken
api | 18:18:03 🌲 request completed 1ms
```

Might be related to node version?

### How do we reproduce the bug?

See above

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.1 - ~\AppData\Local\Temp\xfs-71caf7ba\node.CMD
    Yarn: 3.2.3 - ~\AppData\Local\Temp\xfs-71caf7ba\yarn.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
  npmPackages:
    @redwoodjs/auth-custom-setup: 4.0.0-rc.437 => 4.0.0-rc.437+92c99756d
    @redwoodjs/auth-dbauth-setup: 4.0.0-rc.437 => 4.0.0-rc.437+92c99756d
    @redwoodjs/core: ^4.0.0-rc.437 => 4.0.0-rc.437+92c99756d
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dennemark** [comment]
Also happens with node version 18.12.1 LTS

**Comment by dennemark** [comment]
It is an issue with prisma. Seems like deleting node_modules and yarn.lock and running `yarn install` solves the issue.
https://github.com/prisma/prisma/issues/17070
