### ISSUE TITLE
TypeError: this.splice is not a function (Node v16.14.0)

### ISSUE THREAD

**Issue by mikepage** [redwoodjs/redwood#5526]
After upgrading to Redwood 1.4.0 from 1.3.3 the following api error occurs. Should I modify the autogenerated services or GraphSQL schemas.

``` 
api | 15:28:27 🐛 Execution start
api | 15:28:27 🐛 
api | Received GraphQL operation:
api | 
api | 15:28:27 🐛        operationName:
api | 15:28:27 🐛        variables:
api | 15:28:27 🐛 graphql-server GraphQL execution started: CalendarPropertyTypesQuery
api | 15:28:27 🐛 Execution end
api | 15:28:27 🐛        result:
api | 15:28:27 🐛 graphql-server GraphQL execution completed: CalendarPropertyTypesQuery
api | 15:28:27 🚨 this.splice is not a function 
api | TypeError: this.splice is not a function
api |     at HeadersList.append (/Users/mikepage/git/mikepage/campstaff/node_modules/@graphql-tools/github-loader/node_modules/cross-undici-fetch/dist/patch-headers-list.js:44:16)
api |     at Headers.append (/Users/mikepage/git/mikepage/campstaff/node_modules/undici/lib/fetch/headers.js:232:31)
api |     at new Response (/Users/mikepage/git/mikepage/campstaff/node_modules/undici/lib/fetch/response.js:175:22)
api |     at YogaServer.handleRequest (/Users/mikepage/git/mikepage/campstaff/node_modules/@graphql-yoga/common/index.js:654:34)
api |     at async handlerFn (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:271:24)
api |     at async execFn (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:310:16)
api |     at async requestHandler (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:121:30) 
api | {
api |   "err": {
api |     "type": "TypeError",
api |     "message": "this.splice is not a function",
api |     "stack": "TypeError: this.splice is not a function\n    at HeadersList.append (/Users/mikepage/git/mikepage/campstaff/node_modules/@graphql-tools/github-loader/node_modules/cross-undici-fetch/dist/patch-headers-list.js:44:16)\n    at Headers.append (/Users/mikepage/git/mikepage/campstaff/node_modules/undici/lib/fetch/headers.js:232:31)\n    at new Response (/Users/mikepage/git/mikepage/campstaff/node_modules/undici/lib/fetch/response.js:175:22)\n    at YogaServer.handleRequest (/Users/mikepage/git/mikepage/campstaff/node_modules/@graphql-yoga/common/index.js:654:34)\n    at async handlerFn (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:271:24)\n    at async execFn (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:310:16)\n    at async requestHandler (/Users/mikepage/git/mikepage/campstaff/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:121:30)"
api |   }
api | }
```

**Comment by jtoar** [comment]
Hey @mikepage thanks for providing a reproduction! I'll try to reproduce it now. In the meantime could you post the output for this command here?

```
yarn why cross-undici-fetch
```

And could you try a few basic troubleshooting steps: just remove `node_modules` and run `yarn install`. Then if that doesn't work, remove `yarn.lock` and run `yarn install`.

**Comment by mikepage** [comment]
As you requested the ouput of the command.

```
yarn why cross-undici-fetch

├─ @graphql-tools/apollo-engine-loader@npm:7.2.6
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-tools/apollo-engine-loader@npm:7.2.6 [81fe0]
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-tools/github-loader@npm:7.2.10
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-tools/github-loader@npm:7.2.10 [81fe0]
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-tools/url-loader@npm:7.9.8
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-tools/url-loader@npm:7.9.8 [81fe0]
│  └─ cross-undici-fetch@npm:0.1.28 (via npm:^0.1.19)
│
├─ @graphql-yoga/common@npm:2.5.0
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.2)
│
├─ @graphql-yoga/common@npm:2.5.0 [cb7dd]
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.2)
│
├─ @redwoodjs/api@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/api@npm:1.4.0 [cb7dd]
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/graphql-server@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/prerender@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/prerender@npm:1.4.0 [ea7f1]
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
└─ @redwoodjs/telemetry@npm:1.4.0
   └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
``` 

I will try removing the yarn.lock file, I tried removing node_modules earlier without result.

**Comment by mikepage** [comment]
I have removed the yarn.lock file after rw upgrade, did yarn install and it worked!

``` 
yarn why cross-undici-fetch

├─ @graphql-tools/apollo-engine-loader@npm:7.2.16
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-tools/apollo-engine-loader@npm:7.2.16 [81fe0]
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-tools/github-loader@npm:7.2.20
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-tools/github-loader@npm:7.2.20 [81fe0]
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-tools/url-loader@npm:7.9.21
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-tools/url-loader@npm:7.9.21 [81fe0]
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.0)
│
├─ @graphql-yoga/common@npm:2.5.0
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.2)
│
├─ @graphql-yoga/common@npm:2.5.0 [cb7dd]
│  └─ cross-undici-fetch@npm:0.4.3 (via npm:^0.4.2)
│
├─ @redwoodjs/api@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/api@npm:1.4.0 [cb7dd]
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/graphql-server@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/prerender@npm:1.4.0
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
├─ @redwoodjs/prerender@npm:1.4.0 [ea7f1]
│  └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
│
└─ @redwoodjs/telemetry@npm:1.4.0
   └─ cross-undici-fetch@npm:0.1.27 (via npm:0.1.27)
```

**Comment by jtoar** [comment]
@mikepage awesome! That output you just posted matches what I see on new projects. 👍 I'll see if I can get an update from the guild on `cross-undici-fetch` so that we can upgrade again. We downgraded because of a bug in CORS that was affecting one of our deployment providers.

Ok to close this one since things seem to be working?

**Comment by tal** [comment]
Fwiw I just came across this issue and deleting the lock file seemed to fix it for me too
