### ISSUE TITLE
[Bug?]: can't start storybook on v5

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#8299]
### What's not working?

After upgrading to v5, a user can't start storybook. They get the following error:

```
ModuleParseError: Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function.
File was processed with these loaders: * …/node_modules/@redwoodjs/core/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js * …/node_modules/@redwoodjs/core/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
```

### How do we reproduce the bug?

TBD

### What's your environment? (If it applies)

```shell
TBD
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
The user never followed up with information I could use for debugging so closing for the moment.
